#!/usr/bin/env ruby

require 'daemons'
require 'yaml'
require_relative 'lib/camopticon'

pwd = Dir.pwd
CONFIG = YAML.load_file('config.yml') unless defined? CONFIG

Daemons.run_proc('camopticon', {monitor: true, backtrace: true}) do
  Dir.chdir pwd do
    loop do
      CONFIG['cameras'].each do |camera|
        camopticon = Camopticon.new
        camopticon.camera = camera
        camopticon.storage_path = CONFIG['storage_path']
        camopticon.pushover = CONFIG['pushover']
        camopticon.s3 = CONFIG['s3']
        camopticon.capture_frame
      end
      sleep CONFIG['fps'] ||= 1
    end
  end
end
